########## Builder ##########
FROM golang:1.22-alpine AS builder

# Install the latest version of Delve
RUN go install github.com/go-delve/delve/cmd/dlv@v1.22.1

ENV APP_PATH=/go/src/github.com/anchore/harbor-scanner-adapter

RUN mkdir -p $APP_PATH
WORKDIR $APP_PATH
COPY . $APP_PATH

# Expose debugger
EXPOSE 2345

# Start Delve
CMD /go/bin/dlv --listen=:2345 --headless --accept-multiclient debug $APP_PATH/cmd/anchore-adapter/main.go
